Homepage menu and dummy portfolio
Gujsingh/CSE115A pull request #4
Opened 2022-01-22 12:12 UTC by mihika-marathe

2022-01-22 16:57 UTC, ojas1542 requested changes
Looks good so far. Could you also add a "Settings" option in the menu if the user wants to change their password or some other info?

2022-01-23 00:15 UTC, nreusken approved these changes

2022-01-23 00:37 UTC, nreusken approved these changes

2022-01-23 02:28 UTC, ojas1542 approved these changes

2022-01-23 02:36 UTC, merged